name: Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar projeto
        run: |
          node --version
          npm --version
          npm install

      - name: Build
        run: echo "Build realizado com sucesso"

      - name: SAST - SonarQube
        run: npx sonar-scanner "-Dsonar.token=${{ secrets.SONAR_TOKEN }}"